### ISSUE TITLE
Update 7.2

### ISSUE THREAD

**Issue by BloodDragon2580** [MikeMatt16/Keyed#1]
Dont work anymore with Update to 7.2.
Can you Update this Please.

**Comment by Michampt** [comment]
So I have managed to get Keyed to work with 7.2. I just need all of the new dungeon ID numbers and to find out which byte is now the depleted byte and then I'll see if I can't send it to the OC here.

**Comment by BloodDragon2580** [comment]
how i can find the new dungeons is`s.

**Comment by Michampt** [comment]
If you have elvui, and have item id's shown on tooltips, the keystones tooltip will show in the bottom left as a 3 digit number. for example halls of valor is 200.

Another way is if you have devtools installed you can do /dump GetContainerItemInfo(-Linkyourkeystone-) or /dump GetContainerItemInfo(0,3) if the key is in your main bags third slot.

**Comment by Michampt** [comment]
Update finished, waiting for OC to pull the branch

**Comment by MikeMatt16** [comment]
Great, thanks for the help! I'll push the update out tonight.

On Apr 1, 2017 11:15 AM, "Rauxz" <notifications@github.com> wrote:

Update finished, waiting for OC to pull the branch

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MikeMatt16/Keyed/issues/1#issuecomment-290926352>, or mute
the thread

**Comment by Michampt** [comment]
NP! if you want, before you release it, probably RC or beta it because some of the names might be a bit long now (Karazhan and Cathedral). I'm sending it to a few guildies to help me test it out.

**Comment by Michampt** [comment]
Oh and it still says 1.6 in the corner, I didn't change that.

**Comment by Michampt** [comment]
Seeing some issues on other's computers. I think it's due to old keystones lingering and a clear db doesnt do it because it will pick it right back up from another player. Maybe because of the major changes the db should be renamed going forward?

**Comment by MikeMatt16** [comment]
Yeah or I can implement a check for an old format and then wipe it or
ignore it

**Comment by Michampt** [comment]
Issue was I didn't update the locale for the new 3 dungeons. Fixed and pushed for enUS. The out of date keys button will still give errors. I just tell my guild to not click it for now.
