### ISSUE TITLE
8.0 pre patch

### ISSUE THREAD

**Issue by Redkualid** [MikeMatt16/Keyed#6]
The window does not show the key unless hovered over. Lvl seems to be off, showing 208 for a 16 key. I assume this is more of a wait for BFA release to address the issues with the new keys and ids etc, but wanted to see

**Comment by MikeMatt16** [comment]
I'm aware of the issues, and am currently working on a fix.

**Comment by MikeMatt16** [comment]
I forgot to close this issue, but as of 1.10.0 these issues have been addressed.
